{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[],"gpuType":"T4","authorship_tag":"ABX9TyO8FsPnYWxzyXov8lCxdLmP"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"},"accelerator":"GPU"},"cells":[{"cell_type":"code","source":["%pip install -U -q transformers bitsandbytes accelerate datasets"],"metadata":{"id":"8HYV9qFlWlfD","executionInfo":{"status":"ok","timestamp":1731254895741,"user_tz":-180,"elapsed":4607,"user":{"displayName":"ISY640","userId":"14578547707035782428"}},"colab":{"base_uri":"https://localhost:8080/"},"outputId":"5eeb3ed1-8966-404d-b71f-3634377c3d44"},"execution_count":1,"outputs":[{"output_type":"stream","name":"stdout","text":["\u001b[?25l     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m0.0/44.1 kB\u001b[0m \u001b[31m?\u001b[0m eta \u001b[36m-:--:--\u001b[0m\r\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m44.1/44.1 kB\u001b[0m \u001b[31m1.3 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hTraceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/base_command.py\", line 179, in exc_logging_wrapper\n","    status = run_func(*args)\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/req_command.py\", line 67, in wrapper\n","    return func(self, options, args)\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/commands/install.py\", line 377, in run\n","    requirement_set = resolver.resolve(\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/resolution/resolvelib/resolver.py\", line 95, in resolve\n","    result = self._result = resolver.resolve(\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/resolvelib/resolvers.py\", line 546, in resolve\n","    state = resolution.resolve(requirements, max_rounds=max_rounds)\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/resolvelib/resolvers.py\", line 427, in resolve\n","    failure_causes = self._attempt_to_pin_criterion(name)\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/resolvelib/resolvers.py\", line 239, in _attempt_to_pin_criterion\n","    criteria = self._get_updated_criteria(candidate)\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/resolvelib/resolvers.py\", line 230, in _get_updated_criteria\n","    self._add_to_criteria(criteria, requirement, parent=candidate)\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/resolvelib/resolvers.py\", line 173, in _add_to_criteria\n","    if not criterion.candidates:\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/resolvelib/structs.py\", line 156, in __bool__\n","    return bool(self._sequence)\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/resolution/resolvelib/found_candidates.py\", line 174, in __bool__\n","    return any(self)\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/resolution/resolvelib/found_candidates.py\", line 162, in <genexpr>\n","    return (c for c in iterator if id(c) not in self._incompatible_ids)\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/resolution/resolvelib/found_candidates.py\", line 53, in _iter_built\n","    candidate = func()\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/resolution/resolvelib/factory.py\", line 185, in _make_candidate_from_link\n","    base: Optional[BaseCandidate] = self._make_base_candidate_from_link(\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/resolution/resolvelib/factory.py\", line 231, in _make_base_candidate_from_link\n","    self._link_candidate_cache[link] = LinkCandidate(\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/resolution/resolvelib/candidates.py\", line 272, in __init__\n","    cache_entry = factory.get_wheel_cache_entry(source_link, name)\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/resolution/resolvelib/factory.py\", line 611, in get_wheel_cache_entry\n","    supported_tags=get_supported(),\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/utils/compatibility_tags.py\", line 142, in get_supported\n","    supported.extend(\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/packaging/tags.py\", line 224, in cpython_tags\n","    platforms = list(platforms or platform_tags())\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/packaging/tags.py\", line 499, in _linux_platforms\n","    yield from _manylinux.platform_tags(archs)\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/packaging/_manylinux.py\", line 256, in platform_tags\n","    if _is_compatible(arch, glibc_version):\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/packaging/_manylinux.py\", line 187, in _is_compatible\n","    import _manylinux\n","  File \"<frozen importlib._bootstrap>\", line 1024, in _find_and_load\n","  File \"<frozen importlib._bootstrap>\", line 170, in __enter__\n","  File \"<frozen importlib._bootstrap>\", line 209, in _get_module_lock\n","KeyboardInterrupt\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/bin/pip3\", line 8, in <module>\n","    sys.exit(main())\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/main.py\", line 80, in main\n","    return command.main(cmd_args)\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/base_command.py\", line 100, in main\n","    return self._main(args)\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/base_command.py\", line 232, in _main\n","    return run(options, args)\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/base_command.py\", line 215, in exc_logging_wrapper\n","    logger.critical(\"Operation cancelled by user\")\n","  File \"/usr/lib/python3.10/logging/__init__.py\", line 1524, in critical\n","    self._log(CRITICAL, msg, args, **kwargs)\n","  File \"/usr/lib/python3.10/logging/__init__.py\", line 1624, in _log\n","    self.handle(record)\n","  File \"/usr/lib/python3.10/logging/__init__.py\", line 1634, in handle\n","    self.callHandlers(record)\n","  File \"/usr/lib/python3.10/logging/__init__.py\", line 1696, in callHandlers\n","    hdlr.handle(record)\n","  File \"/usr/lib/python3.10/logging/__init__.py\", line 968, in handle\n","    self.emit(record)\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/utils/logging.py\", line 172, in emit\n","    style = Style(color=\"red\")\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/rich/style.py\", line 146, in __init__\n","    def _make_color(color: Union[Color, str]) -> Color:\n","  File \"/usr/lib/python3.10/typing.py\", line 309, in inner\n","    return cached(*args, **kwds)\n","  File \"/usr/lib/python3.10/typing.py\", line 403, in __getitem__\n","    return self._getitem(self, parameters)\n","  File \"/usr/lib/python3.10/typing.py\", line 521, in Union\n","    return _UnionGenericAlias(self, parameters)\n","  File \"/usr/lib/python3.10/typing.py\", line 1019, in __init__\n","    super().__init__(origin, inst=inst, name=name)\n","  File \"/usr/lib/python3.10/typing.py\", line 949, in __init__\n","    self._name = name\n","  File \"/usr/lib/python3.10/typing.py\", line 989, in __setattr__\n","    super().__setattr__(attr, val)\n","KeyboardInterrupt\n","^C\n"]}]},{"cell_type":"code","execution_count":null,"metadata":{"id":"-9762rSfWVv5"},"outputs":[],"source":["import pandas as pd\n","import numpy as np\n","\n","import torch\n","import torch.nn as nn\n","import torch.nn.functional as F\n","\n","# import bitsandbytes as bnb\n","\n","from transformers import AutoModelForSequenceClassification, TrainingArguments, Trainer, pipeline\n","from datasets import Dataset, DatasetDict"]},{"cell_type":"code","source":["def fast_sentiment(texts):\n","  model = pipeline(model=\"seara/rubert-tiny2-russian-sentiment\")\n","  ans = []\n","  for text in texts:\n","    ans.append(model(text))\n","  return ans"],"metadata":{"id":"tokxpntvWjpe"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["class BERTDataset(Dataset):\n","    def __init__(self, df, tokenizer, max_len):\n","        self.df = df\n","        self.max_len = max_len\n","        self.text = df.Text\n","        self.tokenizer = tokenizer\n","        self.targets = df[target_cols].values\n","\n","    def __len__(self):\n","        return len(self.df)\n","\n","    def __getitem__(self, index):\n","        text = self.text[index]\n","        inputs = self.tokenizer.encode_plus(\n","            text,\n","            truncation=True,\n","            add_special_tokens=True,\n","            max_length=self.max_len,\n","            padding='max_length',\n","            return_token_type_ids=True\n","        )\n","        ids = inputs['input_ids']\n","        mask = inputs['attention_mask']\n","        token_type_ids = inputs[\"token_type_ids\"]\n","\n","        return {\n","            'ids': torch.tensor(ids, dtype=torch.long),\n","            'mask': torch.tensor(mask, dtype=torch.long),\n","            'token_type_ids': torch.tensor(token_type_ids, dtype=torch.long),\n","            'targets': torch.tensor(self.targets[index], dtype=torch.float)\n","        }"],"metadata":{"id":"_jkl-pIx0YR3"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["train_dataset = BERTDataset(df_train, tokenizer, MAX_LEN)\n","valid_dataset = BERTDataset(df_dev, tokenizer, MAX_LEN)"],"metadata":{"id":"f462Ob9w1JRY"},"execution_count":null,"outputs":[]}]}